import {
  FILE_FORMAT_INSTRUCTIONS,
  canCallModel,
  degradedEvent,
  diagnoseModelFailure,
  emptyOutputFailure,
  outOfTimeNote,
  parseFileBlocks,
  pause,
  runAgentCompletion,
  stepBudgetMs,
} from "@/lib/agents/llm";
import type { Agent, AppPlan, GeneratedFile } from "@/lib/agents/types";

const SYSTEM = `You are the Coding Agent in an automated app-building pipeline. The UI and Database agents have already generated the visual layer and schema. You write the remaining application code that wires everything together:

- data access helpers ("src/lib/data.ts") matching the schema
- a REST API route handler under "src/app/api/<table>/route.ts" (GET list + POST create) for each table in the plan's data model
- the root layout ("src/app/layout.tsx") importing globals.css, if not already generated
- project structure files: "package.json" (next/react/tailwind deps, dev/build/start scripts) and "README.md" describing the app, its pages, and how to run it
- any hooks or utilities the plan's features require

Use TypeScript and keep files focused. Do NOT regenerate files that already exist (you'll be given the list).

${FILE_FORMAT_INSTRUCTIONS}`;

function toPascal(snake: string) {
  return snake
    .replace(/_([a-z])/g, (_, c: string) => c.toUpperCase())
    .replace(/^([a-z])/, (c) => c.toUpperCase());
}

function mockFiles(
  plan: AppPlan,
  existingPaths: string[]
): GeneratedFile[] {
  const files: GeneratedFile[] = [
    {
      path: "src/lib/data.ts",
      content: `// Data access helpers wired to the generated schema.
${plan.dataModel
  .map((t) => {
    const type = toPascal(t.table);
    return `
const ${t.table}: unknown[] = [];

export async function list${type}(): Promise<unknown[]> {
  return ${t.table};
}

export async function add${type}(row: unknown): Promise<void> {
  ${t.table}.push(row);
}`;
  })
  .join("\n")}
`,
    },
  ];

  // REST API route per table.
  for (const table of plan.dataModel) {
    const type = toPascal(table.table);
    files.push({
      path: `src/app/api/${table.table}/route.ts`,
      content: `import { NextResponse } from "next/server";

import { add${type}, list${type} } from "@/lib/data";

/** ${table.description} */
export async function GET() {
  return NextResponse.json({ data: await list${type}() });
}

export async function POST(request: Request) {
  const body = await request.json().catch(() => null);
  if (!body) {
    return NextResponse.json({ error: "Invalid body" }, { status: 400 });
  }
  await add${type}(body);
  return NextResponse.json({ success: true }, { status: 201 });
}
`,
    });
  }

  if (!existingPaths.includes("src/app/layout.tsx")) {
    files.push({
      path: "src/app/layout.tsx",
      content: `import "./globals.css";

export const metadata = {
  title: "${plan.appName}",
  description: "${plan.summary.replace(/"/g, "'")}",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="antialiased">{children}</body>
    </html>
  );
}
`,
    });
  }

  // Project structure files.
  files.push(
    {
      path: "package.json",
      content: `${JSON.stringify(
        {
          name: plan.appName.toLowerCase().replace(/[^a-z0-9]+/g, "-"),
          version: "0.1.0",
          private: true,
          scripts: {
            dev: "next dev",
            build: "next build",
            start: "next start",
          },
          dependencies: {
            next: "^15.0.0",
            react: "^19.0.0",
            "react-dom": "^19.0.0",
          },
          devDependencies: {
            tailwindcss: "^4.0.0",
            typescript: "^5.0.0",
          },
        },
        null,
        2
      )}\n`,
    },
    {
      path: "README.md",
      content: `# ${plan.appName}

${plan.summary}

## Pages

${plan.pages.map((p) => `- **${p.name}** (\`${p.path}\`) — ${p.description}`).join("\n")}

## Getting started

\`\`\`bash
npm install
npm run dev
\`\`\`

Generated by App-Creator.
`,
    }
  );

  return files;
}

export const codingAgent: Agent = {
  name: "coding",
  async run(context, emit) {
    emit({
      type: "agent_start",
      agent: "coding",
      message: "Writing application code…",
    });
    const plan = context.plan!;
    const existingPaths = [...context.files.keys()];

    let files: GeneratedFile[];
    let note = "";
    if (!canCallModel(context)) {
      const reason = outOfTimeNote(context);
      if (reason) {
        note = ` (${reason} — wired up from the plan instead)`;
        emit(
          degradedEvent(
            "coding",
            "Your application code is wired up from the plan, not written by a model.",
            diagnoseModelFailure(
              new Error(
                "The build budget ran out before this step could start a model call."
              )
            )
          )
        );
      } else await pause(800);
      files = mockFiles(plan, existingPaths);
    } else {
      try {
        const text = await runAgentCompletion({
          system: SYSTEM,
          // This step emits many whole files at once; the default
          // ceiling truncates it mid-file, and a truncated block used to
          // discard the entire response.
          maxTokens: 16000,
          prompt: [
            `Plan:\n${JSON.stringify(plan, null, 2)}`,
            ...(context.architecture
              ? [`Architecture (follow these paths and conventions):\n${context.architecture}`]
              : []),
            `Files that already exist (do not regenerate):\n${existingPaths.join("\n")}`,
            `Original request: ${context.prompt}`,
          ].join("\n\n"),
          role: "primary-coding",
          timeoutMs: stepBudgetMs(context),
        });
        files = parseFileBlocks(text);
        if (files.length === 0) {
          const failure = emptyOutputFailure(
            "The model's response contained no ===FILE:…===/===END=== blocks, so no code could be read out of it."
          );
          note = ` (${failure.summary} — wired up from the plan instead)`;
          emit(
            degradedEvent(
              "coding",
              "Your application code is wired up from the plan, not written by a model.",
              failure
            )
          );
          files = mockFiles(plan, existingPaths);
        }
      } catch (error) {
        const failure = diagnoseModelFailure(error);
        note = ` (${failure.summary} — wired up from the plan instead)`;
        emit(
          degradedEvent(
            "coding",
            "Your application code is wired up from the plan, not written by a model.",
            failure
          )
        );
        files = mockFiles(plan, existingPaths);
      }
    }

    for (const file of files) {
      context.files.set(file.path, file);
      emit({ type: "file", agent: "coding", path: file.path });
    }
    emit({
      type: "agent_complete",
      agent: "coding",
      message: `Wrote ${files.length} code files${note}`,
    });
  },
};
