import {
  FILE_FORMAT_INSTRUCTIONS,
  isLlmConfigured,
  parseFileBlocks,
  pause,
  runAgentCompletion,
} from "@/lib/agents/llm";
import type { Agent, AppPlan, GeneratedFile } from "@/lib/agents/types";

const SYSTEM = `You are the UI Agent in an automated app-building pipeline. Given a build plan, you generate the visual layer.

Requirements:
1. FIRST generate "preview/index.html" — a complete, SELF-CONTAINED static HTML preview of the app's home page: inline <style> only (no external stylesheets, fonts, scripts, or images), modern polished design, responsive.
2. Then generate each page from the plan as a Next.js App Router page (TypeScript, Tailwind classes) under "src/app".
3. Then generate each component from the plan under "src/components".

${FILE_FORMAT_INSTRUCTIONS}`;

function mockFiles(plan: AppPlan): GeneratedFile[] {
  const previewHtml = `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>${plan.appName}</title>
<style>
  * { margin: 0; box-sizing: border-box; }
  body { font-family: system-ui, sans-serif; color: #18181b; background: #fafafa; }
  .nav { display: flex; justify-content: space-between; align-items: center; padding: 16px 32px; background: #fff; border-bottom: 1px solid #e4e4e7; }
  .brand { font-weight: 700; font-size: 18px; }
  .btn { background: linear-gradient(135deg, #8b5cf6, #d946ef); color: #fff; border: 0; padding: 10px 20px; border-radius: 8px; font-weight: 600; cursor: pointer; }
  .hero { text-align: center; padding: 96px 24px 72px; background: radial-gradient(ellipse at top, rgba(139,92,246,.12), transparent 60%); }
  .hero h1 { font-size: clamp(32px, 6vw, 56px); letter-spacing: -0.03em; }
  .hero p { color: #52525b; max-width: 560px; margin: 16px auto 32px; font-size: 18px; }
  .features { display: grid; grid-template-columns: repeat(auto-fit, minmax(240px, 1fr)); gap: 16px; max-width: 960px; margin: 0 auto; padding: 0 24px 96px; }
  .card { background: #fff; border: 1px solid #e4e4e7; border-radius: 12px; padding: 24px; text-align: left; }
  .card h3 { margin-bottom: 8px; font-size: 16px; }
  .card p { color: #71717a; font-size: 14px; line-height: 1.5; }
  footer { border-top: 1px solid #e4e4e7; padding: 24px; text-align: center; color: #a1a1aa; font-size: 13px; }
</style>
</head>
<body>
  <nav class="nav"><span class="brand">${plan.appName}</span><button class="btn">Get started</button></nav>
  <section class="hero">
    <h1>${plan.appName}</h1>
    <p>${plan.summary}</p>
    <button class="btn">Get started free</button>
  </section>
  <section class="features">
    ${plan.features
      .slice(0, 3)
      .map(
        (f) =>
          `<div class="card"><h3>${f}</h3><p>Built automatically by the App-Creator agent pipeline.</p></div>`
      )
      .join("\n    ")}
  </section>
  <footer>Generated by App-Creator · ${plan.appName}</footer>
</body>
</html>`;

  return [
    { path: "preview/index.html", content: previewHtml },
    {
      path: "src/app/page.tsx",
      content: `import { Hero } from "@/components/hero";
import { FeatureGrid } from "@/components/feature-grid";

export default function HomePage() {
  return (
    <main>
      <Hero />
      <FeatureGrid />
    </main>
  );
}
`,
    },
    {
      path: "src/components/hero.tsx",
      content: `export function Hero() {
  return (
    <section className="px-6 py-24 text-center">
      <h1 className="text-5xl font-semibold tracking-tight">${plan.appName}</h1>
      <p className="mx-auto mt-4 max-w-xl text-lg text-zinc-600">${plan.summary}</p>
      <button className="mt-8 rounded-lg bg-gradient-to-r from-violet-500 to-fuchsia-500 px-6 py-3 font-semibold text-white">
        Get started free
      </button>
    </section>
  );
}
`,
    },
    {
      path: "src/components/feature-grid.tsx",
      content: `const features = ${JSON.stringify(plan.features.slice(0, 3), null, 2)};

export function FeatureGrid() {
  return (
    <section className="mx-auto grid max-w-4xl gap-4 px-6 pb-24 sm:grid-cols-3">
      {features.map((feature) => (
        <div key={feature} className="rounded-xl border p-6">
          <h3 className="font-medium">{feature}</h3>
        </div>
      ))}
    </section>
  );
}
`,
    },
  ];
}

export const uiAgent: Agent = {
  name: "ui",
  async run(context, emit) {
    emit({
      type: "agent_start",
      agent: "ui",
      message: "Generating pages and components…",
    });
    const plan = context.plan!;

    let files: GeneratedFile[];
    if (!isLlmConfigured()) {
      await pause(900);
      files = mockFiles(plan);
    } else {
      const text = await runAgentCompletion({
        system: SYSTEM,
        prompt: `Build plan:\n${JSON.stringify(plan, null, 2)}\n\nOriginal request: ${context.prompt}`,
      });
      files = parseFileBlocks(text);
    }

    for (const file of files) {
      context.files.set(file.path, file);
      emit({ type: "file", agent: "ui", path: file.path });
    }
    emit({
      type: "agent_complete",
      agent: "ui",
      message: `Generated ${files.length} UI files`,
    });
  },
};
